package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"calculator/server/graph/model"
	"context"
	"fmt"
	"strconv"
)

// AddProduct is the resolver for the addProduct field.
func (r *mutationResolver) AddProduct(ctx context.Context, name string, price float64) (*model.Product, error) {
	result, err := r.DB.ExecContext(ctx,
		"INSERT INTO products (name, price) VALUES (?, ?)",
		name, price,
	)
	if err != nil {
		return nil, fmt.Errorf("mahsulot qo'shib bo'lmadi: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return nil, fmt.Errorf("id olishda xato: %w", err)
	}

	var product model.Product
	row := r.DB.QueryRowContext(ctx,
		"SELECT id, name, price, created_at FROM products WHERE id = ?", id,
	)
	var createdAt []byte
	err = row.Scan(&product.ID, &product.Name, &product.Price, &createdAt)
	if err != nil {
		return nil, fmt.Errorf("mahsulot o'qishda xato: %w", err)
	}
	product.CreatedAt = string(createdAt)

	return &product, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, name string, price float64) (*model.Product, error) {
	_, err := r.DB.ExecContext(ctx,
		"UPDATE products SET name = ?, price = ? WHERE id = ?",
		name, price, id,
	)
	if err != nil {
		return nil, fmt.Errorf("mahsulotni yangilab bo'lmadi: %w", err)
	}

	var product model.Product
	row := r.DB.QueryRowContext(ctx,
		"SELECT id, name, price, created_at FROM products WHERE id = ?", id,
	)
	var createdAt []byte
	err = row.Scan(&product.ID, &product.Name, &product.Price, &createdAt)
	if err != nil {
		return nil, fmt.Errorf("mahsulotni qayta o'qishda xato: %w", err)
	}
	product.CreatedAt = string(createdAt)

	return &product, nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	_, err := r.DB.ExecContext(ctx, "DELETE FROM products WHERE id = ?", id)
	if err != nil {
		return false, fmt.Errorf("mahsulotni o'chirib bo'lmadi: %w", err)
	}
	return true, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, firstName string, lastName string) (*model.User, error) {
	result, err := r.DB.ExecContext(ctx,
		"INSERT INTO users (first_name, last_name) VALUES (?, ?)",
		firstName, lastName,
	)
	if err != nil {
		return nil, fmt.Errorf("ishchini qo'shib bo'lmadi: %w", err)
	}

	insertId, err := result.LastInsertId()
	if err != nil {
		return nil, fmt.Errorf("id olishda xato: %w", err)
	}

	var user model.User
	row := r.DB.QueryRowContext(ctx,
		"SELECT id, first_name, last_name, created_at FROM users WHERE id = ?", insertId,
	)
	var createdAt []byte
	err = row.Scan(&user.ID, &user.FirstName, &user.LastName, &createdAt)
	if err != nil {
		return nil, fmt.Errorf("ishchini o'qishda xato: %w", err)
	}
	user.CreatedAt = string(createdAt)

	return &user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, firstName string, lastName string) (*model.User, error) {
	_, err := r.DB.ExecContext(ctx,
		"UPDATE users SET first_name = ?, last_name = ? WHERE id = ?",
		firstName, lastName, id,
	)
	if err != nil {
		return nil, fmt.Errorf("ishchini yangilab bo'lmadi: %w", err)
	}

	var user model.User
	row := r.DB.QueryRowContext(ctx,
		"SELECT id, first_name, last_name, created_at FROM users WHERE id = ?", id,
	)
	var createdAt []byte
	err = row.Scan(&user.ID, &user.FirstName, &user.LastName, &createdAt)
	if err != nil {
		return nil, fmt.Errorf("ishchini qayta o'qishda xato: %w", err)
	}
	user.CreatedAt = string(createdAt)

	return &user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	_, err := r.DB.ExecContext(ctx, "DELETE FROM users WHERE id = ?", id)
	if err != nil {
		return false, fmt.Errorf("ishchini o'chirib bo'lmadi: %w", err)
	}
	return true, nil
}

// AddRecords is the resolver for the addRecords field.
func (r *mutationResolver) AddRecords(ctx context.Context, userID string, items []*model.RecordInput) (bool, error) {
	tx, err := r.DB.BeginTx(ctx, nil)
	if err != nil {
		return false, fmt.Errorf("tranzaksiyani boshlab bo'lmadi: %w", err)
	}
	defer tx.Rollback()

	stmt, err := tx.PrepareContext(ctx, "INSERT INTO records (user_id, product_id, quantity) VALUES (?, ?, ?)")
	if err != nil {
		return false, fmt.Errorf("so'rovni tayyorlab bo'lmadi: %w", err)
	}
	defer stmt.Close()

	for _, item := range items {
		_, err := stmt.ExecContext(ctx, userID, item.ProductID, item.Quantity)
		if err != nil {
			return false, fmt.Errorf("yozuvni saqlab bo'lmadi: %w", err)
		}
	}

	if err := tx.Commit(); err != nil {
		return false, fmt.Errorf("tranzaksiyani saqlab bo'lmadi: %w", err)
	}

	return true, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	rows, err := r.DB.QueryContext(ctx,
		"SELECT id, name, price, created_at FROM products ORDER BY created_at DESC",
	)
	if err != nil {
		return nil, fmt.Errorf("mahsulotlarni o'qib bo'lmadi: %w", err)
	}
	defer rows.Close()

	var products []*model.Product
	for rows.Next() {
		var p model.Product
		var id int64
		var createdAt []byte
		if err := rows.Scan(&id, &p.Name, &p.Price, &createdAt); err != nil {
			return nil, fmt.Errorf("qatorda xato: %w", err)
		}
		p.ID = strconv.FormatInt(id, 10)
		p.CreatedAt = string(createdAt)
		products = append(products, &p)
	}

	return products, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	rows, err := r.DB.QueryContext(ctx,
		"SELECT id, first_name, last_name, created_at FROM users ORDER BY created_at DESC",
	)
	if err != nil {
		return nil, fmt.Errorf("ishchilarni o'qib bo'lmadi: %w", err)
	}
	defer rows.Close()

	var users []*model.User
	for rows.Next() {
		var u model.User
		var uid int64
		var createdAt []byte
		if err := rows.Scan(&uid, &u.FirstName, &u.LastName, &createdAt); err != nil {
			return nil, fmt.Errorf("qatorda xato: %w", err)
		}
		u.ID = strconv.FormatInt(uid, 10)
		u.CreatedAt = string(createdAt)
		users = append(users, &u)
	}

	return users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	var user model.User
	var createdAt []byte
	err := r.DB.QueryRowContext(ctx,
		"SELECT id, first_name, last_name, created_at FROM users WHERE id = ?", id,
	).Scan(&user.ID, &user.FirstName, &user.LastName, &createdAt)
	if err != nil {
		return nil, fmt.Errorf("ishchini topib bo'lmadi: %w", err)
	}
	user.CreatedAt = string(createdAt)

	return &user, nil
}

// Records is the resolver for the records field.
func (r *queryResolver) Records(ctx context.Context) ([]*model.Record, error) {
	query := `
		SELECT 
			r.id, r.quantity, r.created_at,
			u.id, u.first_name, u.last_name, u.created_at,
			p.id, p.name, p.price, p.created_at
		FROM records r
		JOIN users u ON r.user_id = u.id
		JOIN products p ON r.product_id = p.id
		ORDER BY r.created_at DESC
	`
	rows, err := r.DB.QueryContext(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("rekordlarni o'qib bo'lmadi: %w", err)
	}
	defer rows.Close()

	var records []*model.Record
	for rows.Next() {
		var rec model.Record
		var user model.User
		var product model.Product
		var rId int64
		var rCreatedAt []byte
		var uId int64
		var uCreatedAt []byte
		var pId int64
		var pCreatedAt []byte

		err := rows.Scan(
			&rId, &rec.Quantity, &rCreatedAt,
			&uId, &user.FirstName, &user.LastName, &uCreatedAt,
			&pId, &product.Name, &product.Price, &pCreatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("qatorda xato: %w", err)
		}

		rec.ID = strconv.FormatInt(rId, 10)
		rec.CreatedAt = string(rCreatedAt)
		
		user.ID = strconv.FormatInt(uId, 10)
		user.CreatedAt = string(uCreatedAt)
		rec.User = &user

		product.ID = strconv.FormatInt(pId, 10)
		product.CreatedAt = string(pCreatedAt)
		rec.Product = &product

		records = append(records, &rec)
	}

	return records, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
