// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Product struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Price     float64 `json:"price"`
	CreatedAt string  `json:"createdAt"`
}

type Query struct {
}

type Record struct {
	ID        string   `json:"id"`
	User      *User    `json:"user"`
	Product   *Product `json:"product"`
	Quantity  float64  `json:"quantity"`
	CreatedAt string   `json:"createdAt"`
}

type RecordInput struct {
	ProductID string  `json:"productId"`
	Quantity  float64 `json:"quantity"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	CreatedAt string `json:"createdAt"`
}
